account/urls.py
#!/usr/bin/env python
#coding:utf-8
#__time__: 2020/2/26 13:30
#__author__ = 'ren_mcc'
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",success_url="/account/password-change-done"),name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),name='password_change_done'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",email_template_name="account/password_reset_email.html",subject_template_name='account/password_reset_subject.txt',success_url='/account/password-reset-done'), name='password_reset'),
    path('password-reset-done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',success_url="/account/password-reset-complete/"),name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),name="password_reset_complete"),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image', views.my_image, name='my_image'),

]

article/urls.py
#!/usr/bin/env python
#coding:utf-8
#__time__: 2020/2/27 1:45
#__author__ = 'ren_mcc'

from django.urls import path,re_path
from . import views, list_views

urlpatterns = [
    path('', list_views.article_titles),
    path('article-column/',views.article_column, name='article_column'),
    path('rename-column/',views.rename_article_column, name='rename_article_column'),
    path('del-column/',views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/',views.redit_article, name="redit_article"),
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
    path('article-tag/', views.article_tag, name="article_tag"),
    path('del-article-tag/', views.del_article_tag, name="del_article_tag"),

]

blog/urls.py
#!/usr/bin/env python
#coding:utf-8
#__time__: 2020/2/26 2:24
#__author__ = 'ren_mcc'

from django.urls import path
from . import views

urlpatterns = [
    path('blog_title', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_article, name='blog_article')
]

blog2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView


urlpatterns = [
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('blog', include(('blog.urls','blog'),namespace='blog')),
    path('account/', include(('account.urls','account'),namespace='account')),
    path('article/', include(('article.urls','article'), namespace='article')),
    path('course/', include(('course.urls','course'),namespace='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}{% endblock %}
    </body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copyright ren_mcc@foxmail.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
{#            <a  class='navbar-brand' href="http://www.baidu.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>#}
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation" style="margin-left:10px">
                <li><a href="{% url 'home' %}">首页</a></li>
                <li><a href="{% url 'blog:blog_title' %}">Blog</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                    <li><div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div></li>
                    <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">登录</a></li>
                    <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>欢迎</h1>
        <h3>人生苦短，我用python</h3>
        {% load staticfiles %}
        <img src="{% static "images/book.jpg" %}" alt="">
    </div>


{% endblock %}

templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
    <span class="current">
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
    </span>
</div>